Update from v1.3

diff --git a/.github/workflows/pr-path-detection.yml b/.github/workflows/pr-path-detection.yml
--- a/.github/workflows/pr-path-detection.yml
+++ b/.github/workflows/pr-path-detection.yml
@@ -23,29 +23,24 @@ jobs:
       - name: Check the Validity of Hyperlinks
         run: |
           cd ${{github.workspace}}
-          delay=15   # minimum consecutive URL request delay to pass Fortinet Proxy checks
-          timeout=15 # max connect timeout
           fail="FALSE"
           merged_commit=$(git log -1 --format='%H')
           changed_files="$(git diff --name-status --diff-filter=ARM ${{ github.event.pull_request.base.sha }} ${merged_commit} | awk '/\.md$/ {print $NF}')"
           if  [ -n "$changed_files" ]; then
             for changed_file in $changed_files; do
-              echo "URL checks for: $changed_file"
-              url_lines=$(grep -H -Eo '\]\(http[s]?://[^)]+\)' "$changed_file" | sort -u | grep -Ev 'GenAIEval/blob/main') || true
+              url_lines=$(grep -H -Eo '\]\(http[s]?://[^)]+\)' "$changed_file" | grep -Ev 'GenAIEval/blob/main') || true
               if [ -n "$url_lines" ]; then
                 for url_line in $url_lines; do
                   url=$(echo "$url_line"|cut -d '(' -f2 | cut -d ')' -f1|sed 's/\.git$//')
                   path=$(echo "$url_line"|cut -d':' -f1 | cut -d'/' -f2-)
-                  echo "- $url"
-                  sleep $delay
-                  response=$(curl --connect-timeout $timeout -L -s -o /dev/null -w "%{http_code}" "$url")
+                  response=$(curl -L -s -o /dev/null -w "%{http_code}" "$url")
                   if [ "$response" -ne 200 ]; then
-                    echo "**********Validation failed ($response), try again**********"
-                    response_retry=$(curl --connect-timeout $timeout -s -o /dev/null -w "%{http_code}" "$url")
+                    echo "**********Validation failed, try again**********"
+                    response_retry=$(curl -s -o /dev/null -w "%{http_code}" "$url")
                     if [ "$response_retry" -eq 200 ]; then
                       echo "*****Retry successful*****"
                     else
-                      echo "Invalid link ($response_retry) from ${{github.workspace}}/$path: $url"
+                      echo "Invalid link from ${{github.workspace}}/$path: $url"
                       fail="TRUE"
                     fi
                   fi
@@ -53,13 +48,14 @@ jobs:
               fi
             done
           else
-            echo "No changed .md file(s)."
+            echo "No changed .md file."
           fi
 
           if [[ "$fail" == "TRUE" ]]; then
             exit 1
+          else
+            echo "All hyperlinks are valid."
           fi
-          echo "All hyperlinks are valid."
         shell: bash
 
   check-the-validity-of-relative-path:
@@ -79,8 +75,8 @@ jobs:
           fail="FALSE"
           repo_name=${{ github.event.pull_request.head.repo.full_name }}
           if [ "$(echo "$repo_name"|cut -d'/' -f1)" != "opea-project" ]; then
-            repo_fork=$(echo "${{ github.event.pull_request.head.repo.full_name }}" |cut -d/ -f-2)
-            branch="https://github.com/$repo_fork/tree/${{ github.event.pull_request.head.ref }}"
+            owner=$(echo "${{ github.event.pull_request.head.repo.full_name }}" |cut -d'/' -f1)
+            branch="https://github.com/$owner/GenAIInfra/tree/${{ github.event.pull_request.head.ref }}"
           else
             branch="https://github.com/opea-project/GenAIInfra/blob/${{ github.event.pull_request.head.ref }}"
           fi
@@ -88,7 +84,7 @@ jobs:
 
           merged_commit=$(git log -1 --format='%H')
           changed_files="$(git diff --name-status --diff-filter=ARM ${{ github.event.pull_request.base.sha }} ${merged_commit} | awk '/\.md$/ {print $NF}')"
-          png_lines=$(grep -Eo '\]\([^)]+\)' --include='*.md' -r .|grep -Ev 'http'|sort -u)
+          png_lines=$(grep -Eo '\]\([^)]+\)' --include='*.md' -r .|grep -Ev 'http')
           if [ -n "$png_lines" ]; then
             for png_line in $png_lines; do
               refer_path=$(echo "$png_line"|cut -d':' -f1 | cut -d'/' -f2-)
